// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: io_simulation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaultType int32

const (
	FaultType_FAULT_NONE              FaultType = 0
	FaultType_FAULT_PERMISSION_DENIED FaultType = 1
	FaultType_FAULT_INVALID_ADDRESS   FaultType = 2
	FaultType_FAULT_HARDWARE_TIMEOUT  FaultType = 3
	FaultType_FAULT_PATH_TRAVERSAL    FaultType = 4
	FaultType_FAULT_FILE_NOT_FOUND    FaultType = 5
)

// Enum value maps for FaultType.
var (
	FaultType_name = map[int32]string{
		0: "FAULT_NONE",
		1: "FAULT_PERMISSION_DENIED",
		2: "FAULT_INVALID_ADDRESS",
		3: "FAULT_HARDWARE_TIMEOUT",
		4: "FAULT_PATH_TRAVERSAL",
		5: "FAULT_FILE_NOT_FOUND",
	}
	FaultType_value = map[string]int32{
		"FAULT_NONE":              0,
		"FAULT_PERMISSION_DENIED": 1,
		"FAULT_INVALID_ADDRESS":   2,
		"FAULT_HARDWARE_TIMEOUT":  3,
		"FAULT_PATH_TRAVERSAL":    4,
		"FAULT_FILE_NOT_FOUND":    5,
	}
)

func (x FaultType) Enum() *FaultType {
	p := new(FaultType)
	*p = x
	return p
}

func (x FaultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultType) Descriptor() protoreflect.EnumDescriptor {
	return file_io_simulation_proto_enumTypes[0].Descriptor()
}

func (FaultType) Type() protoreflect.EnumType {
	return &file_io_simulation_proto_enumTypes[0]
}

func (x FaultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultType.Descriptor instead.
func (FaultType) EnumDescriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{0}
}

type SimControlCommand_Action int32

const (
	SimControlCommand_ACTION_INIT         SimControlCommand_Action = 0
	SimControlCommand_ACTION_STEP_NEXT    SimControlCommand_Action = 1
	SimControlCommand_ACTION_INJECT_FAULT SimControlCommand_Action = 2
)

// Enum value maps for SimControlCommand_Action.
var (
	SimControlCommand_Action_name = map[int32]string{
		0: "ACTION_INIT",
		1: "ACTION_STEP_NEXT",
		2: "ACTION_INJECT_FAULT",
	}
	SimControlCommand_Action_value = map[string]int32{
		"ACTION_INIT":         0,
		"ACTION_STEP_NEXT":    1,
		"ACTION_INJECT_FAULT": 2,
	}
)

func (x SimControlCommand_Action) Enum() *SimControlCommand_Action {
	p := new(SimControlCommand_Action)
	*p = x
	return p
}

func (x SimControlCommand_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimControlCommand_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_io_simulation_proto_enumTypes[1].Descriptor()
}

func (SimControlCommand_Action) Type() protoreflect.EnumType {
	return &file_io_simulation_proto_enumTypes[1]
}

func (x SimControlCommand_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimControlCommand_Action.Descriptor instead.
func (SimControlCommand_Action) EnumDescriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{0, 0}
}

type SystemSnapshot_Layer int32

const (
	SystemSnapshot_LAYER_USER        SystemSnapshot_Layer = 0
	SystemSnapshot_LAYER_INDEPENDENT SystemSnapshot_Layer = 1
	SystemSnapshot_LAYER_DRIVER      SystemSnapshot_Layer = 2
	SystemSnapshot_LAYER_INTERRUPT   SystemSnapshot_Layer = 3
	SystemSnapshot_LAYER_HARDWARE    SystemSnapshot_Layer = 4
)

// Enum value maps for SystemSnapshot_Layer.
var (
	SystemSnapshot_Layer_name = map[int32]string{
		0: "LAYER_USER",
		1: "LAYER_INDEPENDENT",
		2: "LAYER_DRIVER",
		3: "LAYER_INTERRUPT",
		4: "LAYER_HARDWARE",
	}
	SystemSnapshot_Layer_value = map[string]int32{
		"LAYER_USER":        0,
		"LAYER_INDEPENDENT": 1,
		"LAYER_DRIVER":      2,
		"LAYER_INTERRUPT":   3,
		"LAYER_HARDWARE":    4,
	}
)

func (x SystemSnapshot_Layer) Enum() *SystemSnapshot_Layer {
	p := new(SystemSnapshot_Layer)
	*p = x
	return p
}

func (x SystemSnapshot_Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemSnapshot_Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_io_simulation_proto_enumTypes[2].Descriptor()
}

func (SystemSnapshot_Layer) Type() protoreflect.EnumType {
	return &file_io_simulation_proto_enumTypes[2]
}

func (x SystemSnapshot_Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemSnapshot_Layer.Descriptor instead.
func (SystemSnapshot_Layer) EnumDescriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{3, 0}
}

type ProcessBlock_State int32

const (
	ProcessBlock_STATE_RUNNING ProcessBlock_State = 0
	ProcessBlock_STATE_BLOCKED ProcessBlock_State = 1
	ProcessBlock_STATE_READY   ProcessBlock_State = 2
)

// Enum value maps for ProcessBlock_State.
var (
	ProcessBlock_State_name = map[int32]string{
		0: "STATE_RUNNING",
		1: "STATE_BLOCKED",
		2: "STATE_READY",
	}
	ProcessBlock_State_value = map[string]int32{
		"STATE_RUNNING": 0,
		"STATE_BLOCKED": 1,
		"STATE_READY":   2,
	}
)

func (x ProcessBlock_State) Enum() *ProcessBlock_State {
	p := new(ProcessBlock_State)
	*p = x
	return p
}

func (x ProcessBlock_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessBlock_State) Descriptor() protoreflect.EnumDescriptor {
	return file_io_simulation_proto_enumTypes[3].Descriptor()
}

func (ProcessBlock_State) Type() protoreflect.EnumType {
	return &file_io_simulation_proto_enumTypes[3]
}

func (x ProcessBlock_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessBlock_State.Descriptor instead.
func (ProcessBlock_State) EnumDescriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{4, 0}
}

type SimControlCommand struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Action        SimControlCommand_Action `protobuf:"varint,1,opt,name=action,proto3,enum=io_simulator.SimControlCommand_Action" json:"action,omitempty"`
	Config        *ReadRequestConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	InjectedFault FaultType                `protobuf:"varint,3,opt,name=injected_fault,json=injectedFault,proto3,enum=io_simulator.FaultType" json:"injected_fault,omitempty"`
	UserContext   *UserContext             `protobuf:"bytes,4,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimControlCommand) Reset() {
	*x = SimControlCommand{}
	mi := &file_io_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimControlCommand) ProtoMessage() {}

func (x *SimControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimControlCommand.ProtoReflect.Descriptor instead.
func (*SimControlCommand) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimControlCommand) GetAction() SimControlCommand_Action {
	if x != nil {
		return x.Action
	}
	return SimControlCommand_ACTION_INIT
}

func (x *SimControlCommand) GetConfig() *ReadRequestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SimControlCommand) GetInjectedFault() FaultType {
	if x != nil {
		return x.InjectedFault
	}
	return FaultType_FAULT_NONE
}

func (x *SimControlCommand) GetUserContext() *UserContext {
	if x != nil {
		return x.UserContext
	}
	return nil
}

type ReadRequestConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilePath        string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	BytesToRead     uint32                 `protobuf:"varint,2,opt,name=bytes_to_read,json=bytesToRead,proto3" json:"bytes_to_read,omitempty"`
	UserBufferAddr  uint64                 `protobuf:"varint,3,opt,name=user_buffer_addr,json=userBufferAddr,proto3" json:"user_buffer_addr,omitempty"`
	UseDoubleBuffer bool                   `protobuf:"varint,4,opt,name=use_double_buffer,json=useDoubleBuffer,proto3" json:"use_double_buffer,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadRequestConfig) Reset() {
	*x = ReadRequestConfig{}
	mi := &file_io_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestConfig) ProtoMessage() {}

func (x *ReadRequestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestConfig.ProtoReflect.Descriptor instead.
func (*ReadRequestConfig) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRequestConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ReadRequestConfig) GetBytesToRead() uint32 {
	if x != nil {
		return x.BytesToRead
	}
	return 0
}

func (x *ReadRequestConfig) GetUserBufferAddr() uint64 {
	if x != nil {
		return x.UserBufferAddr
	}
	return 0
}

func (x *ReadRequestConfig) GetUseDoubleBuffer() bool {
	if x != nil {
		return x.UseDoubleBuffer
	}
	return false
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	HomeDir       string                 `protobuf:"bytes,4,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_io_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *UserContext) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserContext) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *UserContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserContext) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

type SystemSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentActiveLayer SystemSnapshot_Layer   `protobuf:"varint,1,opt,name=current_active_layer,json=currentActiveLayer,proto3,enum=io_simulator.SystemSnapshot_Layer" json:"current_active_layer,omitempty"`
	StepDescription    string                 `protobuf:"bytes,2,opt,name=step_description,json=stepDescription,proto3" json:"step_description,omitempty"`
	ProcessState       *ProcessBlock          `protobuf:"bytes,3,opt,name=process_state,json=processState,proto3" json:"process_state,omitempty"`
	MemoryState        *MemoryView            `protobuf:"bytes,4,opt,name=memory_state,json=memoryState,proto3" json:"memory_state,omitempty"`
	HardwareState      *HardwareView          `protobuf:"bytes,5,opt,name=hardware_state,json=hardwareState,proto3" json:"hardware_state,omitempty"`
	IsFinished         bool                   `protobuf:"varint,6,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	FinalErrorCode     string                 `protobuf:"bytes,7,opt,name=final_error_code,json=finalErrorCode,proto3" json:"final_error_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemSnapshot) Reset() {
	*x = SystemSnapshot{}
	mi := &file_io_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSnapshot) ProtoMessage() {}

func (x *SystemSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSnapshot.ProtoReflect.Descriptor instead.
func (*SystemSnapshot) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *SystemSnapshot) GetCurrentActiveLayer() SystemSnapshot_Layer {
	if x != nil {
		return x.CurrentActiveLayer
	}
	return SystemSnapshot_LAYER_USER
}

func (x *SystemSnapshot) GetStepDescription() string {
	if x != nil {
		return x.StepDescription
	}
	return ""
}

func (x *SystemSnapshot) GetProcessState() *ProcessBlock {
	if x != nil {
		return x.ProcessState
	}
	return nil
}

func (x *SystemSnapshot) GetMemoryState() *MemoryView {
	if x != nil {
		return x.MemoryState
	}
	return nil
}

func (x *SystemSnapshot) GetHardwareState() *HardwareView {
	if x != nil {
		return x.HardwareState
	}
	return nil
}

func (x *SystemSnapshot) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *SystemSnapshot) GetFinalErrorCode() string {
	if x != nil {
		return x.FinalErrorCode
	}
	return ""
}

type ProcessBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	State         ProcessBlock_State     `protobuf:"varint,2,opt,name=state,proto3,enum=io_simulator.ProcessBlock_State" json:"state,omitempty"`
	WaitReason    string                 `protobuf:"bytes,3,opt,name=wait_reason,json=waitReason,proto3" json:"wait_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessBlock) Reset() {
	*x = ProcessBlock{}
	mi := &file_io_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBlock) ProtoMessage() {}

func (x *ProcessBlock) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBlock.ProtoReflect.Descriptor instead.
func (*ProcessBlock) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessBlock) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessBlock) GetState() ProcessBlock_State {
	if x != nil {
		return x.State
	}
	return ProcessBlock_STATE_RUNNING
}

func (x *ProcessBlock) GetWaitReason() string {
	if x != nil {
		return x.WaitReason
	}
	return ""
}

type MemoryView struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserBufferData     []byte                 `protobuf:"bytes,1,opt,name=user_buffer_data,json=userBufferData,proto3" json:"user_buffer_data,omitempty"`
	KernelBuffer_1Data []byte                 `protobuf:"bytes,2,opt,name=kernel_buffer_1_data,json=kernelBuffer1Data,proto3" json:"kernel_buffer_1_data,omitempty"`
	KernelBuffer_2Data []byte                 `protobuf:"bytes,3,opt,name=kernel_buffer_2_data,json=kernelBuffer2Data,proto3" json:"kernel_buffer_2_data,omitempty"`
	CurrentIrpInfo     string                 `protobuf:"bytes,4,opt,name=current_irp_info,json=currentIrpInfo,proto3" json:"current_irp_info,omitempty"`
	ActiveWriteBuffer  int32                  `protobuf:"varint,5,opt,name=active_write_buffer,json=activeWriteBuffer,proto3" json:"active_write_buffer,omitempty"`
	ActiveReadBuffer   int32                  `protobuf:"varint,6,opt,name=active_read_buffer,json=activeReadBuffer,proto3" json:"active_read_buffer,omitempty"`
	CurrentChunk       int32                  `protobuf:"varint,7,opt,name=current_chunk,json=currentChunk,proto3" json:"current_chunk,omitempty"`
	TotalChunks        int32                  `protobuf:"varint,8,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MemoryView) Reset() {
	*x = MemoryView{}
	mi := &file_io_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryView) ProtoMessage() {}

func (x *MemoryView) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryView.ProtoReflect.Descriptor instead.
func (*MemoryView) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryView) GetUserBufferData() []byte {
	if x != nil {
		return x.UserBufferData
	}
	return nil
}

func (x *MemoryView) GetKernelBuffer_1Data() []byte {
	if x != nil {
		return x.KernelBuffer_1Data
	}
	return nil
}

func (x *MemoryView) GetKernelBuffer_2Data() []byte {
	if x != nil {
		return x.KernelBuffer_2Data
	}
	return nil
}

func (x *MemoryView) GetCurrentIrpInfo() string {
	if x != nil {
		return x.CurrentIrpInfo
	}
	return ""
}

func (x *MemoryView) GetActiveWriteBuffer() int32 {
	if x != nil {
		return x.ActiveWriteBuffer
	}
	return 0
}

func (x *MemoryView) GetActiveReadBuffer() int32 {
	if x != nil {
		return x.ActiveReadBuffer
	}
	return 0
}

func (x *MemoryView) GetCurrentChunk() int32 {
	if x != nil {
		return x.CurrentChunk
	}
	return 0
}

func (x *MemoryView) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type HardwareView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CmdRegister    string                 `protobuf:"bytes,1,opt,name=cmd_register,json=cmdRegister,proto3" json:"cmd_register,omitempty"`
	StatusRegister string                 `protobuf:"bytes,2,opt,name=status_register,json=statusRegister,proto3" json:"status_register,omitempty"`
	DataRegister   []byte                 `protobuf:"bytes,3,opt,name=data_register,json=dataRegister,proto3" json:"data_register,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HardwareView) Reset() {
	*x = HardwareView{}
	mi := &file_io_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareView) ProtoMessage() {}

func (x *HardwareView) ProtoReflect() protoreflect.Message {
	mi := &file_io_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareView.ProtoReflect.Descriptor instead.
func (*HardwareView) Descriptor() ([]byte, []int) {
	return file_io_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *HardwareView) GetCmdRegister() string {
	if x != nil {
		return x.CmdRegister
	}
	return ""
}

func (x *HardwareView) GetStatusRegister() string {
	if x != nil {
		return x.StatusRegister
	}
	return ""
}

func (x *HardwareView) GetDataRegister() []byte {
	if x != nil {
		return x.DataRegister
	}
	return nil
}

var File_io_simulation_proto protoreflect.FileDescriptor

const file_io_simulation_proto_rawDesc = "" +
	"\n" +
	"\x13io_simulation.proto\x12\fio_simulator\"\xd4\x02\n" +
	"\x11SimControlCommand\x12>\n" +
	"\x06action\x18\x01 \x01(\x0e2&.io_simulator.SimControlCommand.ActionR\x06action\x127\n" +
	"\x06config\x18\x02 \x01(\v2\x1f.io_simulator.ReadRequestConfigR\x06config\x12>\n" +
	"\x0einjected_fault\x18\x03 \x01(\x0e2\x17.io_simulator.FaultTypeR\rinjectedFault\x12<\n" +
	"\fuser_context\x18\x04 \x01(\v2\x19.io_simulator.UserContextR\vuserContext\"H\n" +
	"\x06Action\x12\x0f\n" +
	"\vACTION_INIT\x10\x00\x12\x14\n" +
	"\x10ACTION_STEP_NEXT\x10\x01\x12\x17\n" +
	"\x13ACTION_INJECT_FAULT\x10\x02\"\xaa\x01\n" +
	"\x11ReadRequestConfig\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\"\n" +
	"\rbytes_to_read\x18\x02 \x01(\rR\vbytesToRead\x12(\n" +
	"\x10user_buffer_addr\x18\x03 \x01(\x04R\x0euserBufferAddr\x12*\n" +
	"\x11use_double_buffer\x18\x04 \x01(\bR\x0fuseDoubleBuffer\"h\n" +
	"\vUserContext\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\rR\x03gid\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\bhome_dir\x18\x04 \x01(\tR\ahomeDir\"\x88\x04\n" +
	"\x0eSystemSnapshot\x12T\n" +
	"\x14current_active_layer\x18\x01 \x01(\x0e2\".io_simulator.SystemSnapshot.LayerR\x12currentActiveLayer\x12)\n" +
	"\x10step_description\x18\x02 \x01(\tR\x0fstepDescription\x12?\n" +
	"\rprocess_state\x18\x03 \x01(\v2\x1a.io_simulator.ProcessBlockR\fprocessState\x12;\n" +
	"\fmemory_state\x18\x04 \x01(\v2\x18.io_simulator.MemoryViewR\vmemoryState\x12A\n" +
	"\x0ehardware_state\x18\x05 \x01(\v2\x1a.io_simulator.HardwareViewR\rhardwareState\x12\x1f\n" +
	"\vis_finished\x18\x06 \x01(\bR\n" +
	"isFinished\x12(\n" +
	"\x10final_error_code\x18\a \x01(\tR\x0efinalErrorCode\"i\n" +
	"\x05Layer\x12\x0e\n" +
	"\n" +
	"LAYER_USER\x10\x00\x12\x15\n" +
	"\x11LAYER_INDEPENDENT\x10\x01\x12\x10\n" +
	"\fLAYER_DRIVER\x10\x02\x12\x13\n" +
	"\x0fLAYER_INTERRUPT\x10\x03\x12\x12\n" +
	"\x0eLAYER_HARDWARE\x10\x04\"\xb9\x01\n" +
	"\fProcessBlock\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x126\n" +
	"\x05state\x18\x02 \x01(\x0e2 .io_simulator.ProcessBlock.StateR\x05state\x12\x1f\n" +
	"\vwait_reason\x18\x03 \x01(\tR\n" +
	"waitReason\">\n" +
	"\x05State\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x00\x12\x11\n" +
	"\rSTATE_BLOCKED\x10\x01\x12\x0f\n" +
	"\vSTATE_READY\x10\x02\"\xe8\x02\n" +
	"\n" +
	"MemoryView\x12(\n" +
	"\x10user_buffer_data\x18\x01 \x01(\fR\x0euserBufferData\x12/\n" +
	"\x14kernel_buffer_1_data\x18\x02 \x01(\fR\x11kernelBuffer1Data\x12/\n" +
	"\x14kernel_buffer_2_data\x18\x03 \x01(\fR\x11kernelBuffer2Data\x12(\n" +
	"\x10current_irp_info\x18\x04 \x01(\tR\x0ecurrentIrpInfo\x12.\n" +
	"\x13active_write_buffer\x18\x05 \x01(\x05R\x11activeWriteBuffer\x12,\n" +
	"\x12active_read_buffer\x18\x06 \x01(\x05R\x10activeReadBuffer\x12#\n" +
	"\rcurrent_chunk\x18\a \x01(\x05R\fcurrentChunk\x12!\n" +
	"\ftotal_chunks\x18\b \x01(\x05R\vtotalChunks\"\x7f\n" +
	"\fHardwareView\x12!\n" +
	"\fcmd_register\x18\x01 \x01(\tR\vcmdRegister\x12'\n" +
	"\x0fstatus_register\x18\x02 \x01(\tR\x0estatusRegister\x12#\n" +
	"\rdata_register\x18\x03 \x01(\fR\fdataRegister*\xa3\x01\n" +
	"\tFaultType\x12\x0e\n" +
	"\n" +
	"FAULT_NONE\x10\x00\x12\x1b\n" +
	"\x17FAULT_PERMISSION_DENIED\x10\x01\x12\x19\n" +
	"\x15FAULT_INVALID_ADDRESS\x10\x02\x12\x1a\n" +
	"\x16FAULT_HARDWARE_TIMEOUT\x10\x03\x12\x18\n" +
	"\x14FAULT_PATH_TRAVERSAL\x10\x04\x12\x18\n" +
	"\x14FAULT_FILE_NOT_FOUND\x10\x052k\n" +
	"\x12IOSimulationEngine\x12U\n" +
	"\x10StreamSimulation\x12\x1f.io_simulator.SimControlCommand\x1a\x1c.io_simulator.SystemSnapshot(\x010\x01B\n" +
	"Z\b./api/pbb\x06proto3"

var (
	file_io_simulation_proto_rawDescOnce sync.Once
	file_io_simulation_proto_rawDescData []byte
)

func file_io_simulation_proto_rawDescGZIP() []byte {
	file_io_simulation_proto_rawDescOnce.Do(func() {
		file_io_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_simulation_proto_rawDesc), len(file_io_simulation_proto_rawDesc)))
	})
	return file_io_simulation_proto_rawDescData
}

var file_io_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_io_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_io_simulation_proto_goTypes = []any{
	(FaultType)(0),                // 0: io_simulator.FaultType
	(SimControlCommand_Action)(0), // 1: io_simulator.SimControlCommand.Action
	(SystemSnapshot_Layer)(0),     // 2: io_simulator.SystemSnapshot.Layer
	(ProcessBlock_State)(0),       // 3: io_simulator.ProcessBlock.State
	(*SimControlCommand)(nil),     // 4: io_simulator.SimControlCommand
	(*ReadRequestConfig)(nil),     // 5: io_simulator.ReadRequestConfig
	(*UserContext)(nil),           // 6: io_simulator.UserContext
	(*SystemSnapshot)(nil),        // 7: io_simulator.SystemSnapshot
	(*ProcessBlock)(nil),          // 8: io_simulator.ProcessBlock
	(*MemoryView)(nil),            // 9: io_simulator.MemoryView
	(*HardwareView)(nil),          // 10: io_simulator.HardwareView
}
var file_io_simulation_proto_depIdxs = []int32{
	1,  // 0: io_simulator.SimControlCommand.action:type_name -> io_simulator.SimControlCommand.Action
	5,  // 1: io_simulator.SimControlCommand.config:type_name -> io_simulator.ReadRequestConfig
	0,  // 2: io_simulator.SimControlCommand.injected_fault:type_name -> io_simulator.FaultType
	6,  // 3: io_simulator.SimControlCommand.user_context:type_name -> io_simulator.UserContext
	2,  // 4: io_simulator.SystemSnapshot.current_active_layer:type_name -> io_simulator.SystemSnapshot.Layer
	8,  // 5: io_simulator.SystemSnapshot.process_state:type_name -> io_simulator.ProcessBlock
	9,  // 6: io_simulator.SystemSnapshot.memory_state:type_name -> io_simulator.MemoryView
	10, // 7: io_simulator.SystemSnapshot.hardware_state:type_name -> io_simulator.HardwareView
	3,  // 8: io_simulator.ProcessBlock.state:type_name -> io_simulator.ProcessBlock.State
	4,  // 9: io_simulator.IOSimulationEngine.StreamSimulation:input_type -> io_simulator.SimControlCommand
	7,  // 10: io_simulator.IOSimulationEngine.StreamSimulation:output_type -> io_simulator.SystemSnapshot
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_io_simulation_proto_init() }
func file_io_simulation_proto_init() {
	if File_io_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_simulation_proto_rawDesc), len(file_io_simulation_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_io_simulation_proto_goTypes,
		DependencyIndexes: file_io_simulation_proto_depIdxs,
		EnumInfos:         file_io_simulation_proto_enumTypes,
		MessageInfos:      file_io_simulation_proto_msgTypes,
	}.Build()
	File_io_simulation_proto = out.File
	file_io_simulation_proto_goTypes = nil
	file_io_simulation_proto_depIdxs = nil
}
