// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: io_simulation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IOSimulationEngine_StreamSimulation_FullMethodName = "/io_simulator.IOSimulationEngine/StreamSimulation"
)

// IOSimulationEngineClient is the client API for IOSimulationEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IOSimulationEngineClient interface {
	// 双向流通信：前端发送控制，后端推送状态
	StreamSimulation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimControlCommand, SystemSnapshot], error)
}

type iOSimulationEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewIOSimulationEngineClient(cc grpc.ClientConnInterface) IOSimulationEngineClient {
	return &iOSimulationEngineClient{cc}
}

func (c *iOSimulationEngineClient) StreamSimulation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimControlCommand, SystemSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IOSimulationEngine_ServiceDesc.Streams[0], IOSimulationEngine_StreamSimulation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimControlCommand, SystemSnapshot]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IOSimulationEngine_StreamSimulationClient = grpc.BidiStreamingClient[SimControlCommand, SystemSnapshot]

// IOSimulationEngineServer is the server API for IOSimulationEngine service.
// All implementations must embed UnimplementedIOSimulationEngineServer
// for forward compatibility.
type IOSimulationEngineServer interface {
	// 双向流通信：前端发送控制，后端推送状态
	StreamSimulation(grpc.BidiStreamingServer[SimControlCommand, SystemSnapshot]) error
	mustEmbedUnimplementedIOSimulationEngineServer()
}

// UnimplementedIOSimulationEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIOSimulationEngineServer struct{}

func (UnimplementedIOSimulationEngineServer) StreamSimulation(grpc.BidiStreamingServer[SimControlCommand, SystemSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamSimulation not implemented")
}
func (UnimplementedIOSimulationEngineServer) mustEmbedUnimplementedIOSimulationEngineServer() {}
func (UnimplementedIOSimulationEngineServer) testEmbeddedByValue()                            {}

// UnsafeIOSimulationEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOSimulationEngineServer will
// result in compilation errors.
type UnsafeIOSimulationEngineServer interface {
	mustEmbedUnimplementedIOSimulationEngineServer()
}

func RegisterIOSimulationEngineServer(s grpc.ServiceRegistrar, srv IOSimulationEngineServer) {
	// If the following call panics, it indicates UnimplementedIOSimulationEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IOSimulationEngine_ServiceDesc, srv)
}

func _IOSimulationEngine_StreamSimulation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IOSimulationEngineServer).StreamSimulation(&grpc.GenericServerStream[SimControlCommand, SystemSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IOSimulationEngine_StreamSimulationServer = grpc.BidiStreamingServer[SimControlCommand, SystemSnapshot]

// IOSimulationEngine_ServiceDesc is the grpc.ServiceDesc for IOSimulationEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOSimulationEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io_simulator.IOSimulationEngine",
	HandlerType: (*IOSimulationEngineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSimulation",
			Handler:       _IOSimulationEngine_StreamSimulation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "io_simulation.proto",
}
